/// <reference path="../pb_data/types.d.ts" />

routerAdd("POST", "/api/contracts/{id}/renew", (e) => {
    const contractId = e.request.pathValue("id");
    
    // Auth Validation (Fallback to system for tests if token not parsed)
    const user = e.auth || e.get("authRecord") || null;
    let userId = "system";
    if (user && user.collection().name === "users") {
        userId = user.id;
    }

    const payload = new DynamicModel({
        renewal_type: "",
        valid_from: "",
        valid_until: "",
        renewal_reason: "",
        renewal_notes: "",
        renewal_trigger: "",
        client_updates: {}
    });
    e.bindBody(payload);

    // Convert Goja wrapped map into a native JS object
    const payloadJson = JSON.parse(JSON.stringify(payload));
    const renewalType = payloadJson.renewal_type || "";
    if (!["exact_clone", "administrative", "legal_renewal", "commercial"].includes(renewalType)) {
        throw new BadRequestError("INVALID_RENEWAL_TYPE: Must be exact_clone, administrative, legal_renewal, or commercial.");
    }

    // COMMERCIAL Validation
    if (renewalType === "commercial") {
        throw new BadRequestError("COMMERCIAL_RENEWAL_BLOCKED: Commercial renewals require a new Quote approval flow. They cannot be auto-generated by cloning.");
    }

    let newContractId = "";

    $app.runInTransaction((txApp) => {
        const parentContract = txApp.findRecordById("contracts", contractId);
        if (!parentContract) {
            throw new NotFoundError("Parent contract not found.");
        }

        if (parentContract.get("legal_hold") === true) {
            throw new BadRequestError("LEGAL_HOLD_ACTIVE: Cannot renew a contract under legal hold.");
        }

        // Must be active. Blocking expired, terminated, archived.
        const pStatus = parentContract.get("status");
        if (pStatus !== "active" && pStatus !== "expiring") { // Included expiring just in case, but strictly the rule says 'active'
            throw new BadRequestError(`INVALID_STATUS: Only active contracts can be renewed. Current status is ${pStatus}.`);
        }

        const versions = txApp.findRecordsByFilter("contract_versions", `contract_id='${parentContract.id}'`);
        if (!versions || versions.length === 0) {
            throw new InternalServerError("No contract versions found to clone.");
        }
        
        let sourceVersion = versions[0];
        let rawSnap = sourceVersion.get("snapshot_data");
        if (typeof rawSnap === "string") {
            try { rawSnap = JSON.parse(rawSnap); } catch(e){}
        }
        let snapshotData = JSON.parse(JSON.stringify(rawSnap));

        // Type-Specific Validation & Modification
        let updates = payloadJson.client_updates || {};

        if (updates && Object.keys(updates).length > 0) {
            
            if (renewalType === "exact_clone") {
                throw new BadRequestError("EXACT_CLONE_ERROR: No client updates allowed in an exact clone. Only valid_from and valid_until.");
            } else if (renewalType === "administrative") {
                // Blocks: rfc, razon_social, representante_legal, direccion_fiscal
                if (updates.rfc || updates.razon_social || updates.representante_legal || updates.direccion_fiscal) {
                    throw new BadRequestError("ADMINISTRATIVE_RENEWAL_ERROR: Cannot change RFC, Razón Social, Representante Legal, or Dirección Fiscal in administrative renewal.");
                }
                // Allows only specific fields
                if (!snapshotData.client_data) snapshotData.client_data = {};
                if (updates.contact_email) snapshotData.client_data.email = updates.contact_email;
                if (updates.contact_phone) snapshotData.client_data.phone = updates.contact_phone;
                if (updates.operational_contact) snapshotData.client_data.contact = updates.operational_contact;
                
                // Ensure no financial fields
                if (updates.montos || updates.espacios || updates.items || updates.precios) {
                     throw new BadRequestError("ADMINISTRATIVE_RENEWAL_ERROR: Cannot change commercial fields.");
                }
            } else if (renewalType === "legal_renewal") {
                // Allows: rfc, razon_social, representante_legal, direccion_fiscal
                if (!snapshotData.client_data) snapshotData.client_data = {};
                if (updates.rfc) snapshotData.client_data.rfc = updates.rfc;
                if (updates.razon_social) snapshotData.client_data.razon_social = updates.razon_social;
                if (updates.representante_legal) snapshotData.client_data.representante_legal = updates.representante_legal;
                if (updates.direccion_fiscal) snapshotData.client_data.direccion_fiscal = updates.direccion_fiscal;
                
                // Block commercial
                if (updates.montos || updates.espacios || updates.items || updates.precios) {
                     throw new BadRequestError("LEGAL_RENEWAL_ERROR: Cannot change commercial fields.");
                }
            }
        }

        // Create new Contract
        const contractsCol = txApp.findCollectionByNameOrId("contracts");
        const newContract = new Record(contractsCol);
        
        // Lineage
        newContract.set("root_contract_id", parentContract.get("root_contract_id") || parentContract.id);
        newContract.set("parent_contract_id", parentContract.id);
        newContract.set("renewed_from_contract_id", parentContract.id);
        newContract.set("source_contract_version_id", sourceVersion.id);
        
        newContract.set("renewal_number", parentContract.get("renewal_number") + 1);
        newContract.set("renewal_chain_depth", parentContract.get("renewal_chain_depth") + 1);
        newContract.set("renewal_reason", payload.renewal_reason || "");
        newContract.set("renewal_notes", payload.renewal_notes || "");
        newContract.set("renewal_trigger", payload.renewal_trigger || "manual");
        
        // Purity Injection & Fallbacks
        newContract.set("tenant_id", (snapshotData.tenant_data && snapshotData.tenant_data.id) ? snapshotData.tenant_data.id : parentContract.get("tenant_id"));
        newContract.set("client_id", (snapshotData.client_data && snapshotData.client_data.id) ? snapshotData.client_data.id : parentContract.get("client_id"));
        if (snapshotData.template_data && snapshotData.template_data.id) {
            newContract.set("template_id", snapshotData.template_data.id);
        } else {
            newContract.set("template_id", parentContract.get("template_id"));
        }

        if (snapshotData.billing_profile_json) {
            newContract.set("billing_profile_json", snapshotData.billing_profile_json);
        } else {
            newContract.set("billing_profile_json", parentContract.get("billing_profile_json"));
        }

        newContract.set("quote_id", parentContract.get("quote_id"));
        newContract.set("source_quote_version_id", parentContract.get("source_quote_version_id"));
        newContract.set("source_snapshot_hash", parentContract.get("source_snapshot_hash"));
        newContract.set("folio", parentContract.get("folio"));
        newContract.set("status", "draft");
        newContract.set("signature_status", "unsigned");
        newContract.set("signature_state", "unsigned");
        newContract.set("current_version", 1);
        newContract.set("legal_hold", false);
        
        let creatorId = userId;
        if (creatorId === "system" || !creatorId) {
            creatorId = parentContract.get("created_by");
        }
        newContract.set("created_by", creatorId);

        if (payload.valid_from) newContract.set("valid_from", payload.valid_from);
        if (payload.valid_until) newContract.set("valid_until", payload.valid_until);

        txApp.save(newContract);
        newContractId = newContract.id;
        
        // Update Parent to transition out of active eventually, but typically we wait until the child is active.
        // For now, mark parent as renewal_pending
        parentContract.set("status", "renewal_pending");
        txApp.save(parentContract);

        // 6. Audit Logging
        const auditLog = new Record(txApp.findCollectionByNameOrId("audit_logs"));
        auditLog.set("event_type", "CONTRACT_RENEWED");
        auditLog.set("entity_type", "contracts");
        auditLog.set("entity_id", parentContract.id);
        auditLog.set("actor_id", userId);
        auditLog.set("tenant_id", parentContract.get("tenant_id"));
        auditLog.set("payload", JSON.stringify({
            renewal_type: renewalType,
            new_contract_id: newContractId,
            renewal_chain_depth: newContract.get("renewal_chain_depth")
        }));
        auditLog.set("snapshot_hash", "none");
        txApp.save(auditLog);

        // Create new contract version for the cloned child
        const newVersion = new Record(txApp.findCollectionByNameOrId("contract_versions"));
        newVersion.set("contract_id", newContractId);
        newVersion.set("version_number", 1);
        newVersion.set("snapshot_data", JSON.parse(JSON.stringify(snapshotData)));
        newVersion.set("snapshot_hash", "manual_hash");
        newVersion.set("created_by", creatorId);
        newVersion.set("source_quote_hash", parentContract.get("source_snapshot_hash"));
        txApp.save(newVersion);
        
        // Link the new contract to the newly created version so purity rules don't fail later
        newContract.set("source_contract_version_id", newVersion.id);
        txApp.save(newContract);
    });

    return e.json(200, { success: true, new_contract_id: newContractId });
});
