import { createApp } from 'vue';
import { createPinia } from 'pinia';
import router from './router';
import PrimeVue from 'primevue/config';
// import Aura from '@primevue/themes/aura';
import './style.css';
import App from './App.vue';

import { setupPermissionDirective } from './directives/v-permission';

const app = createApp(App);
const pinia = createPinia();

app.use(pinia);
app.use(router);
setupPermissionDirective(app);

app.use(PrimeVue, {
    unstyled: true
});
import ToastService from 'primevue/toastservice';
import DsActionBar from './components/ui/DsActionBar.vue';
import DsAlert from './components/ui/DsAlert.vue';
import DsBadge from './components/ui/DsBadge.vue';
import DsButton from './components/ui/DsButton.vue';
import DsCalendarShell from './components/ui/DsCalendarShell.vue';
import DsCard from './components/ui/DsCard.vue';
import DsCheckbox from './components/ui/DsCheckbox.vue';
import DsColumn from './components/ui/DsColumn.vue';
import DsColumnConfig from './components/ui/DsColumnConfig.vue';
import DsConfirmDialog from './components/ui/DsConfirmDialog.vue';
import DsCurrencyInput from './components/ui/DsCurrencyInput.vue';
import DsDatePicker from './components/ui/DsDatePicker.vue';
import DsDocumentToolbar from './components/ui/DsDocumentToolbar.vue';
import DsDocumentViewer from './components/ui/DsDocumentViewer.vue';
import DsDrawer from './components/ui/DsDrawer.vue';
import DsEmptyState from './components/ui/DsEmptyState.vue';
import DsFilters from './components/ui/DsFilters.vue';
import DsFormField from './components/ui/DsFormField.vue';
import DsInput from './components/ui/DsInput.vue';
import DsInputNumber from './components/ui/DsInputNumber.vue';
import DsLoadingState from './components/ui/DsLoadingState.vue';
import DsModal from './components/ui/DsModal.vue';
import DsMultiSelect from './components/ui/DsMultiSelect.vue';
import DsNotificationItem from './components/ui/DsNotificationItem.vue';
import DsNotificationPanel from './components/ui/DsNotificationPanel.vue';
import DsPageHeader from './components/ui/DsPageHeader.vue';
import DsPagination from './components/ui/DsPagination.vue';
import DsProgressSpinner from './components/ui/DsProgressSpinner.vue';
import DsRadio from './components/ui/DsRadio.vue';
import DsSearchBar from './components/ui/DsSearchBar.vue';
import DsSelect from './components/ui/DsSelect.vue';
import DsSkeleton from './components/ui/DsSkeleton.vue';
import DsStatusBadge from './components/ui/DsStatusBadge.vue';
import DsTable from './components/ui/DsTable.vue';
import DsTabs from './components/ui/DsTabs.vue';
import DsTag from './components/ui/DsTag.vue';
import DsTextarea from './components/ui/DsTextarea.vue';
import DsToast from './components/ui/DsToast.vue';
import BaseButton from './components/base/BaseButton.vue';
import BaseDataTable from './components/base/BaseDataTable.vue';
import BaseDocumentViewer from './components/base/BaseDocumentViewer.vue';
import BaseEmptyState from './components/base/BaseEmptyState.vue';
import BaseErrorState from './components/base/BaseErrorState.vue';
import BaseInput from './components/base/BaseInput.vue';
import BaseLoadingState from './components/base/BaseLoadingState.vue';
import BaseModal from './components/base/BaseModal.vue';
import BaseNotificationCenter from './components/base/BaseNotificationCenter.vue';
import BasePageHeader from './components/base/BasePageHeader.vue';
import BasePermissionGuard from './components/base/BasePermissionGuard.vue';
import BaseSelect from './components/base/BaseSelect.vue';
import BaseTextarea from './components/base/BaseTextarea.vue';
import BaseWorkflowTimeline from './components/base/BaseWorkflowTimeline.vue';
import { defineAsyncComponent } from 'vue';

app.use(ToastService);
app.component('FileUploader', defineAsyncComponent(() => import('./components/FileUploader.vue')));
app.component('DsActionBar', DsActionBar);
app.component('DsAlert', DsAlert);
app.component('DsBadge', DsBadge);
app.component('DsButton', DsButton);
app.component('DsCalendarShell', DsCalendarShell);
app.component('DsCard', DsCard);
app.component('DsCheckbox', DsCheckbox);
app.component('DsColumn', DsColumn);
app.component('DsColumnConfig', DsColumnConfig);
app.component('DsConfirmDialog', DsConfirmDialog);
app.component('DsCurrencyInput', DsCurrencyInput);
app.component('DsDatePicker', DsDatePicker);
app.component('DsDocumentToolbar', DsDocumentToolbar);
app.component('DsDocumentViewer', DsDocumentViewer);
app.component('DsDrawer', DsDrawer);
app.component('DsEmptyState', DsEmptyState);
app.component('DsFilters', DsFilters);
app.component('DsFormField', DsFormField);
app.component('DsInput', DsInput);
app.component('DsInputNumber', DsInputNumber);
app.component('DsLoadingState', DsLoadingState);
app.component('DsModal', DsModal);
app.component('DsMultiSelect', DsMultiSelect);
app.component('DsNotificationItem', DsNotificationItem);
app.component('DsNotificationPanel', DsNotificationPanel);
app.component('DsPageHeader', DsPageHeader);
app.component('DsPagination', DsPagination);
app.component('DsProgressSpinner', DsProgressSpinner);
app.component('DsRadio', DsRadio);
app.component('DsSearchBar', DsSearchBar);
app.component('DsSelect', DsSelect);
app.component('DsSkeleton', DsSkeleton);
app.component('DsStatusBadge', DsStatusBadge);
app.component('DsTable', DsTable);
app.component('DsTabs', DsTabs);
app.component('DsTag', DsTag);
app.component('DsTextarea', DsTextarea);
app.component('DsToast', DsToast);
app.component('BaseButton', BaseButton);
app.component('BaseInput', BaseInput);
app.component('BaseSelect', BaseSelect);
app.component('BaseTextarea', BaseTextarea);
app.component('BaseModal', BaseModal);
app.component('BaseDataTable', BaseDataTable);
app.component('BasePageHeader', BasePageHeader);
app.component('BasePermissionGuard', BasePermissionGuard);
app.component('BaseWorkflowTimeline', BaseWorkflowTimeline);
app.component('BaseDocumentViewer', BaseDocumentViewer);
app.component('BaseNotificationCenter', BaseNotificationCenter);
app.component('BaseEmptyState', BaseEmptyState);
app.component('BaseErrorState', BaseErrorState);
app.component('BaseLoadingState', BaseLoadingState);
app.mount('#app');
