import { PrismaService } from '../prisma/prisma.service';
import { Prisma } from '@prisma/client';
export declare class AgreementsRepository {
    private readonly prisma;
    constructor(prisma: PrismaService);
    create(data: Prisma.AgreementUncheckedCreateInput): Promise<{
        id: string;
        tenantId: string;
        createdAt: Date;
        updatedAt: Date;
        deletedAt: Date | null;
        deletedBy: string | null;
        status: import(".prisma/client").$Enums.AgreementStatusEnum;
        description: string | null;
        correlationId: string | null;
        traceId: string | null;
        type: import(".prisma/client").$Enums.AgreementType;
        title: string;
        validFrom: Date | null;
        validUntil: Date | null;
        value: Prisma.Decimal | null;
        currencyCode: string | null;
        clientId: string;
    }>;
    findManyByTenant(tenantId: string, filters?: {
        clientId?: string;
        status?: string;
        type?: string;
    }): Promise<({
        items: {
            id: string;
            tenantId: string;
            createdAt: Date;
            updatedAt: Date;
            deletedAt: Date | null;
            deletedBy: string | null;
            description: string;
            currencyCode: string | null;
            amount: Prisma.Decimal;
            agreementId: string;
            quantity: Prisma.Decimal;
            unitPrice: Prisma.Decimal;
            sortOrder: number;
        }[];
        versions: {
            id: string;
            tenantId: string;
            createdAt: Date;
            updatedAt: Date;
            deletedAt: Date | null;
            deletedBy: string | null;
            payload: Prisma.JsonValue | null;
            agreementId: string;
            versionNumber: number;
            contentHash: string;
            changeDescription: string | null;
        }[];
    } & {
        id: string;
        tenantId: string;
        createdAt: Date;
        updatedAt: Date;
        deletedAt: Date | null;
        deletedBy: string | null;
        status: import(".prisma/client").$Enums.AgreementStatusEnum;
        description: string | null;
        correlationId: string | null;
        traceId: string | null;
        type: import(".prisma/client").$Enums.AgreementType;
        title: string;
        validFrom: Date | null;
        validUntil: Date | null;
        value: Prisma.Decimal | null;
        currencyCode: string | null;
        clientId: string;
    })[]>;
    findById(tenantId: string, id: string): Promise<{
        approvals: {
            id: string;
            tenantId: string;
            createdAt: Date;
            updatedAt: Date;
            deletedAt: Date | null;
            deletedBy: string | null;
            status: import(".prisma/client").$Enums.AgreementStatusEnum;
            decidedAt: Date | null;
            agreementId: string;
            approverId: string;
            comments: string | null;
        }[];
        signatures: {
            id: string;
            tenantId: string;
            createdAt: Date;
            updatedAt: Date;
            deletedAt: Date | null;
            deletedBy: string | null;
            signatureHash: string | null;
            ipAddress: string | null;
            signedAt: Date;
            signatureData: string;
            agreementId: string;
            signerId: string;
            userAgent: string | null;
        }[];
        snapshots: {
            id: string;
            tenantId: string;
            createdAt: Date;
            updatedAt: Date;
            deletedAt: Date | null;
            deletedBy: string | null;
            agreementId: string;
            snapshotData: Prisma.JsonValue;
        }[];
        items: {
            id: string;
            tenantId: string;
            createdAt: Date;
            updatedAt: Date;
            deletedAt: Date | null;
            deletedBy: string | null;
            description: string;
            currencyCode: string | null;
            amount: Prisma.Decimal;
            agreementId: string;
            quantity: Prisma.Decimal;
            unitPrice: Prisma.Decimal;
            sortOrder: number;
        }[];
        evidences: {
            id: string;
            tenantId: string;
            createdAt: Date;
            updatedAt: Date;
            deletedAt: Date | null;
            deletedBy: string | null;
            documentHash: string | null;
            agreementId: string;
            evidenceUrl: string;
            evidenceType: string | null;
        }[];
        versions: {
            id: string;
            tenantId: string;
            createdAt: Date;
            updatedAt: Date;
            deletedAt: Date | null;
            deletedBy: string | null;
            payload: Prisma.JsonValue | null;
            agreementId: string;
            versionNumber: number;
            contentHash: string;
            changeDescription: string | null;
        }[];
    } & {
        id: string;
        tenantId: string;
        createdAt: Date;
        updatedAt: Date;
        deletedAt: Date | null;
        deletedBy: string | null;
        status: import(".prisma/client").$Enums.AgreementStatusEnum;
        description: string | null;
        correlationId: string | null;
        traceId: string | null;
        type: import(".prisma/client").$Enums.AgreementType;
        title: string;
        validFrom: Date | null;
        validUntil: Date | null;
        value: Prisma.Decimal | null;
        currencyCode: string | null;
        clientId: string;
    }>;
    update(tenantId: string, id: string, data: Prisma.AgreementUncheckedUpdateInput): Promise<{
        id: string;
        tenantId: string;
        createdAt: Date;
        updatedAt: Date;
        deletedAt: Date | null;
        deletedBy: string | null;
        status: import(".prisma/client").$Enums.AgreementStatusEnum;
        description: string | null;
        correlationId: string | null;
        traceId: string | null;
        type: import(".prisma/client").$Enums.AgreementType;
        title: string;
        validFrom: Date | null;
        validUntil: Date | null;
        value: Prisma.Decimal | null;
        currencyCode: string | null;
        clientId: string;
    }>;
    addItems(tenantId: string, agreementId: string, items: {
        description: string;
    }[]): Promise<Prisma.BatchPayload>;
    createVersion(data: Prisma.AgreementVersionUncheckedCreateInput): Promise<{
        id: string;
        tenantId: string;
        createdAt: Date;
        updatedAt: Date;
        deletedAt: Date | null;
        deletedBy: string | null;
        payload: Prisma.JsonValue | null;
        agreementId: string;
        versionNumber: number;
        contentHash: string;
        changeDescription: string | null;
    }>;
    getLatestVersion(tenantId: string, agreementId: string): Promise<{
        id: string;
        tenantId: string;
        createdAt: Date;
        updatedAt: Date;
        deletedAt: Date | null;
        deletedBy: string | null;
        payload: Prisma.JsonValue | null;
        agreementId: string;
        versionNumber: number;
        contentHash: string;
        changeDescription: string | null;
    } | null>;
    createApproval(data: Prisma.AgreementApprovalUncheckedCreateInput): Promise<{
        id: string;
        tenantId: string;
        createdAt: Date;
        updatedAt: Date;
        deletedAt: Date | null;
        deletedBy: string | null;
        status: import(".prisma/client").$Enums.AgreementStatusEnum;
        decidedAt: Date | null;
        agreementId: string;
        approverId: string;
        comments: string | null;
    }>;
    createSignature(data: Prisma.AgreementSignatureUncheckedCreateInput): Promise<{
        id: string;
        tenantId: string;
        createdAt: Date;
        updatedAt: Date;
        deletedAt: Date | null;
        deletedBy: string | null;
        signatureHash: string | null;
        ipAddress: string | null;
        signedAt: Date;
        signatureData: string;
        agreementId: string;
        signerId: string;
        userAgent: string | null;
    }>;
    createEvidence(data: Prisma.AgreementEvidenceUncheckedCreateInput): Promise<{
        id: string;
        tenantId: string;
        createdAt: Date;
        updatedAt: Date;
        deletedAt: Date | null;
        deletedBy: string | null;
        documentHash: string | null;
        agreementId: string;
        evidenceUrl: string;
        evidenceType: string | null;
    }>;
    createSnapshot(data: Prisma.AgreementSnapshotUncheckedCreateInput): Promise<{
        id: string;
        tenantId: string;
        createdAt: Date;
        updatedAt: Date;
        deletedAt: Date | null;
        deletedBy: string | null;
        agreementId: string;
        snapshotData: Prisma.JsonValue;
    }>;
}
