import { EventEmitter2 } from '@nestjs/event-emitter';
import { AgreementsRepository } from './agreements.repository';
import { CreateAgreementDto } from './dto/create-agreement.dto';
export declare class AgreementsService {
    private readonly repository;
    private readonly eventEmitter;
    constructor(repository: AgreementsRepository, eventEmitter: EventEmitter2);
    create(tenantId: string, dto: CreateAgreementDto, userId: string): Promise<{
        id: string;
        tenantId: string;
        createdAt: Date;
        updatedAt: Date;
        deletedAt: Date | null;
        deletedBy: string | null;
        status: import(".prisma/client").$Enums.AgreementStatusEnum;
        description: string | null;
        correlationId: string | null;
        traceId: string | null;
        type: import(".prisma/client").$Enums.AgreementType;
        title: string;
        validFrom: Date | null;
        validUntil: Date | null;
        value: import("@prisma/client/runtime/library").Decimal | null;
        currencyCode: string | null;
        clientId: string;
    }>;
    submitForReview(tenantId: string, id: string, userId: string): Promise<{
        id: string;
        tenantId: string;
        createdAt: Date;
        updatedAt: Date;
        deletedAt: Date | null;
        deletedBy: string | null;
        status: import(".prisma/client").$Enums.AgreementStatusEnum;
        description: string | null;
        correlationId: string | null;
        traceId: string | null;
        type: import(".prisma/client").$Enums.AgreementType;
        title: string;
        validFrom: Date | null;
        validUntil: Date | null;
        value: import("@prisma/client/runtime/library").Decimal | null;
        currencyCode: string | null;
        clientId: string;
    }>;
    approve(tenantId: string, id: string, userId: string): Promise<{
        id: string;
        tenantId: string;
        createdAt: Date;
        updatedAt: Date;
        deletedAt: Date | null;
        deletedBy: string | null;
        status: import(".prisma/client").$Enums.AgreementStatusEnum;
        description: string | null;
        correlationId: string | null;
        traceId: string | null;
        type: import(".prisma/client").$Enums.AgreementType;
        title: string;
        validFrom: Date | null;
        validUntil: Date | null;
        value: import("@prisma/client/runtime/library").Decimal | null;
        currencyCode: string | null;
        clientId: string;
    }>;
    reject(tenantId: string, id: string, userId: string, reason: string): Promise<{
        id: string;
        tenantId: string;
        createdAt: Date;
        updatedAt: Date;
        deletedAt: Date | null;
        deletedBy: string | null;
        status: import(".prisma/client").$Enums.AgreementStatusEnum;
        description: string | null;
        correlationId: string | null;
        traceId: string | null;
        type: import(".prisma/client").$Enums.AgreementType;
        title: string;
        validFrom: Date | null;
        validUntil: Date | null;
        value: import("@prisma/client/runtime/library").Decimal | null;
        currencyCode: string | null;
        clientId: string;
    }>;
    generateLetter(tenantId: string, id: string, versionId: string): Promise<{
        id: string;
        tenantId: string;
        createdAt: Date;
        updatedAt: Date;
        deletedAt: Date | null;
        deletedBy: string | null;
        status: import(".prisma/client").$Enums.AgreementStatusEnum;
        description: string | null;
        correlationId: string | null;
        traceId: string | null;
        type: import(".prisma/client").$Enums.AgreementType;
        title: string;
        validFrom: Date | null;
        validUntil: Date | null;
        value: import("@prisma/client/runtime/library").Decimal | null;
        currencyCode: string | null;
        clientId: string;
    }>;
    pendingSignature(tenantId: string, id: string): Promise<{
        id: string;
        tenantId: string;
        createdAt: Date;
        updatedAt: Date;
        deletedAt: Date | null;
        deletedBy: string | null;
        status: import(".prisma/client").$Enums.AgreementStatusEnum;
        description: string | null;
        correlationId: string | null;
        traceId: string | null;
        type: import(".prisma/client").$Enums.AgreementType;
        title: string;
        validFrom: Date | null;
        validUntil: Date | null;
        value: import("@prisma/client/runtime/library").Decimal | null;
        currencyCode: string | null;
        clientId: string;
    }>;
    markAsSigned(tenantId: string, id: string, signatureId: string): Promise<{
        id: string;
        tenantId: string;
        createdAt: Date;
        updatedAt: Date;
        deletedAt: Date | null;
        deletedBy: string | null;
        status: import(".prisma/client").$Enums.AgreementStatusEnum;
        description: string | null;
        correlationId: string | null;
        traceId: string | null;
        type: import(".prisma/client").$Enums.AgreementType;
        title: string;
        validFrom: Date | null;
        validUntil: Date | null;
        value: import("@prisma/client/runtime/library").Decimal | null;
        currencyCode: string | null;
        clientId: string;
    }>;
    activate(tenantId: string, id: string, validFrom: Date, validUntil: Date): Promise<{
        id: string;
        tenantId: string;
        createdAt: Date;
        updatedAt: Date;
        deletedAt: Date | null;
        deletedBy: string | null;
        status: import(".prisma/client").$Enums.AgreementStatusEnum;
        description: string | null;
        correlationId: string | null;
        traceId: string | null;
        type: import(".prisma/client").$Enums.AgreementType;
        title: string;
        validFrom: Date | null;
        validUntil: Date | null;
        value: import("@prisma/client/runtime/library").Decimal | null;
        currencyCode: string | null;
        clientId: string;
    }>;
    complete(tenantId: string, id: string): Promise<{
        id: string;
        tenantId: string;
        createdAt: Date;
        updatedAt: Date;
        deletedAt: Date | null;
        deletedBy: string | null;
        status: import(".prisma/client").$Enums.AgreementStatusEnum;
        description: string | null;
        correlationId: string | null;
        traceId: string | null;
        type: import(".prisma/client").$Enums.AgreementType;
        title: string;
        validFrom: Date | null;
        validUntil: Date | null;
        value: import("@prisma/client/runtime/library").Decimal | null;
        currencyCode: string | null;
        clientId: string;
    }>;
    cancel(tenantId: string, id: string, reason: string): Promise<{
        id: string;
        tenantId: string;
        createdAt: Date;
        updatedAt: Date;
        deletedAt: Date | null;
        deletedBy: string | null;
        status: import(".prisma/client").$Enums.AgreementStatusEnum;
        description: string | null;
        correlationId: string | null;
        traceId: string | null;
        type: import(".prisma/client").$Enums.AgreementType;
        title: string;
        validFrom: Date | null;
        validUntil: Date | null;
        value: import("@prisma/client/runtime/library").Decimal | null;
        currencyCode: string | null;
        clientId: string;
    }>;
}
