import { AgreementsService } from './agreements.service';
import { CreateAgreementDto } from './dto/create-agreement.dto';
export declare class AgreementsController {
    private readonly agreementsService;
    constructor(agreementsService: AgreementsService);
    create(user: any, dto: CreateAgreementDto): Promise<{
        id: string;
        tenantId: string;
        createdAt: Date;
        updatedAt: Date;
        deletedAt: Date | null;
        deletedBy: string | null;
        status: import(".prisma/client").$Enums.AgreementStatusEnum;
        description: string | null;
        correlationId: string | null;
        traceId: string | null;
        type: import(".prisma/client").$Enums.AgreementType;
        title: string;
        validFrom: Date | null;
        validUntil: Date | null;
        value: import("@prisma/client/runtime/library").Decimal | null;
        currencyCode: string | null;
        clientId: string;
    }>;
    submitForReview(user: any, id: string): Promise<{
        id: string;
        tenantId: string;
        createdAt: Date;
        updatedAt: Date;
        deletedAt: Date | null;
        deletedBy: string | null;
        status: import(".prisma/client").$Enums.AgreementStatusEnum;
        description: string | null;
        correlationId: string | null;
        traceId: string | null;
        type: import(".prisma/client").$Enums.AgreementType;
        title: string;
        validFrom: Date | null;
        validUntil: Date | null;
        value: import("@prisma/client/runtime/library").Decimal | null;
        currencyCode: string | null;
        clientId: string;
    }>;
    approve(user: any, id: string): Promise<{
        id: string;
        tenantId: string;
        createdAt: Date;
        updatedAt: Date;
        deletedAt: Date | null;
        deletedBy: string | null;
        status: import(".prisma/client").$Enums.AgreementStatusEnum;
        description: string | null;
        correlationId: string | null;
        traceId: string | null;
        type: import(".prisma/client").$Enums.AgreementType;
        title: string;
        validFrom: Date | null;
        validUntil: Date | null;
        value: import("@prisma/client/runtime/library").Decimal | null;
        currencyCode: string | null;
        clientId: string;
    }>;
    generateLetter(user: any, id: string, versionId: string): Promise<{
        id: string;
        tenantId: string;
        createdAt: Date;
        updatedAt: Date;
        deletedAt: Date | null;
        deletedBy: string | null;
        status: import(".prisma/client").$Enums.AgreementStatusEnum;
        description: string | null;
        correlationId: string | null;
        traceId: string | null;
        type: import(".prisma/client").$Enums.AgreementType;
        title: string;
        validFrom: Date | null;
        validUntil: Date | null;
        value: import("@prisma/client/runtime/library").Decimal | null;
        currencyCode: string | null;
        clientId: string;
    }>;
    pendingSignature(user: any, id: string): Promise<{
        id: string;
        tenantId: string;
        createdAt: Date;
        updatedAt: Date;
        deletedAt: Date | null;
        deletedBy: string | null;
        status: import(".prisma/client").$Enums.AgreementStatusEnum;
        description: string | null;
        correlationId: string | null;
        traceId: string | null;
        type: import(".prisma/client").$Enums.AgreementType;
        title: string;
        validFrom: Date | null;
        validUntil: Date | null;
        value: import("@prisma/client/runtime/library").Decimal | null;
        currencyCode: string | null;
        clientId: string;
    }>;
    markAsSigned(user: any, id: string, signatureId: string): Promise<{
        id: string;
        tenantId: string;
        createdAt: Date;
        updatedAt: Date;
        deletedAt: Date | null;
        deletedBy: string | null;
        status: import(".prisma/client").$Enums.AgreementStatusEnum;
        description: string | null;
        correlationId: string | null;
        traceId: string | null;
        type: import(".prisma/client").$Enums.AgreementType;
        title: string;
        validFrom: Date | null;
        validUntil: Date | null;
        value: import("@prisma/client/runtime/library").Decimal | null;
        currencyCode: string | null;
        clientId: string;
    }>;
}
