import { SpacesRepository } from './spaces.repository';
import { DomainEventPublisher } from '../common/events/domain-event-publisher';
import { Prisma } from '@prisma/client';
import { CreateSpaceDto } from './dto/create-space.dto';
import { UpdateSpaceDto } from './dto/update-space.dto';
export declare class SpacesService {
    private readonly repo;
    private readonly eventPublisher;
    constructor(repo: SpacesRepository, eventPublisher: DomainEventPublisher);
    create(data: CreateSpaceDto): Promise<{
        id: string;
        tenantId: string;
        createdAt: Date;
        updatedAt: Date;
        deletedAt: Date | null;
        deletedBy: string | null;
        name: string;
        regulationTemplate: string;
        code: string | null;
        capacity: number;
        areaSqm: Prisma.Decimal;
        basePricePerHour: Prisma.Decimal;
        configB2b: Prisma.JsonValue;
        preciosPorDia: Prisma.JsonValue;
        diasBloqueados: Prisma.JsonValue;
        impuestosIds: string[];
        status: import(".prisma/client").$Enums.SpaceStatus;
        description: string;
        color: string | null;
        tags: Prisma.JsonValue;
        spaceType: string;
        material: string | null;
        width: Prisma.Decimal | null;
        height: Prisma.Decimal | null;
        measureUnit: string | null;
        location: string | null;
        allowsAgreement: boolean;
        planoPdf: string;
        geographicMap: string | null;
        isDigital: boolean;
        images: Prisma.JsonValue;
    }>;
    findById(id: string): Promise<{
        id: string;
        tenantId: string;
        createdAt: Date;
        updatedAt: Date;
        deletedAt: Date | null;
        deletedBy: string | null;
        name: string;
        regulationTemplate: string;
        code: string | null;
        capacity: number;
        areaSqm: Prisma.Decimal;
        basePricePerHour: Prisma.Decimal;
        configB2b: Prisma.JsonValue;
        preciosPorDia: Prisma.JsonValue;
        diasBloqueados: Prisma.JsonValue;
        impuestosIds: string[];
        status: import(".prisma/client").$Enums.SpaceStatus;
        description: string;
        color: string | null;
        tags: Prisma.JsonValue;
        spaceType: string;
        material: string | null;
        width: Prisma.Decimal | null;
        height: Prisma.Decimal | null;
        measureUnit: string | null;
        location: string | null;
        allowsAgreement: boolean;
        planoPdf: string;
        geographicMap: string | null;
        isDigital: boolean;
        images: Prisma.JsonValue;
    } | null>;
    update(id: string, data: UpdateSpaceDto): Promise<{
        id: string;
        tenantId: string;
        createdAt: Date;
        updatedAt: Date;
        deletedAt: Date | null;
        deletedBy: string | null;
        name: string;
        regulationTemplate: string;
        code: string | null;
        capacity: number;
        areaSqm: Prisma.Decimal;
        basePricePerHour: Prisma.Decimal;
        configB2b: Prisma.JsonValue;
        preciosPorDia: Prisma.JsonValue;
        diasBloqueados: Prisma.JsonValue;
        impuestosIds: string[];
        status: import(".prisma/client").$Enums.SpaceStatus;
        description: string;
        color: string | null;
        tags: Prisma.JsonValue;
        spaceType: string;
        material: string | null;
        width: Prisma.Decimal | null;
        height: Prisma.Decimal | null;
        measureUnit: string | null;
        location: string | null;
        allowsAgreement: boolean;
        planoPdf: string;
        geographicMap: string | null;
        isDigital: boolean;
        images: Prisma.JsonValue;
    }>;
}
