import { SpacesService } from './spaces.service';
import { Prisma } from '@prisma/client';
import { CreateSpaceDto } from './dto/create-space.dto';
import { UpdateSpaceDto } from './dto/update-space.dto';
import { Request } from 'express';
interface AuthenticatedRequest extends Request {
    user: {
        id: string;
        tenantId: string;
        role: string;
        permissions: string[];
    };
}
export declare class SpacesController {
    private readonly spacesService;
    constructor(spacesService: SpacesService);
    create(req: AuthenticatedRequest, data: CreateSpaceDto): Promise<{
        id: string;
        tenantId: string;
        createdAt: Date;
        updatedAt: Date;
        deletedAt: Date | null;
        deletedBy: string | null;
        name: string;
        regulationTemplate: string;
        code: string | null;
        capacity: number;
        areaSqm: Prisma.Decimal;
        basePricePerHour: Prisma.Decimal;
        configB2b: Prisma.JsonValue;
        preciosPorDia: Prisma.JsonValue;
        diasBloqueados: Prisma.JsonValue;
        impuestosIds: string[];
        status: import(".prisma/client").$Enums.SpaceStatus;
        description: string;
        color: string | null;
        tags: Prisma.JsonValue;
        spaceType: string;
        material: string | null;
        width: Prisma.Decimal | null;
        height: Prisma.Decimal | null;
        measureUnit: string | null;
        location: string | null;
        allowsAgreement: boolean;
        planoPdf: string;
        geographicMap: string | null;
        isDigital: boolean;
        images: Prisma.JsonValue;
    }>;
    findById(req: AuthenticatedRequest, id: string): Promise<{
        id: string;
        tenantId: string;
        createdAt: Date;
        updatedAt: Date;
        deletedAt: Date | null;
        deletedBy: string | null;
        name: string;
        regulationTemplate: string;
        code: string | null;
        capacity: number;
        areaSqm: Prisma.Decimal;
        basePricePerHour: Prisma.Decimal;
        configB2b: Prisma.JsonValue;
        preciosPorDia: Prisma.JsonValue;
        diasBloqueados: Prisma.JsonValue;
        impuestosIds: string[];
        status: import(".prisma/client").$Enums.SpaceStatus;
        description: string;
        color: string | null;
        tags: Prisma.JsonValue;
        spaceType: string;
        material: string | null;
        width: Prisma.Decimal | null;
        height: Prisma.Decimal | null;
        measureUnit: string | null;
        location: string | null;
        allowsAgreement: boolean;
        planoPdf: string;
        geographicMap: string | null;
        isDigital: boolean;
        images: Prisma.JsonValue;
    } | null>;
    update(req: AuthenticatedRequest, id: string, data: UpdateSpaceDto): Promise<{
        id: string;
        tenantId: string;
        createdAt: Date;
        updatedAt: Date;
        deletedAt: Date | null;
        deletedBy: string | null;
        name: string;
        regulationTemplate: string;
        code: string | null;
        capacity: number;
        areaSqm: Prisma.Decimal;
        basePricePerHour: Prisma.Decimal;
        configB2b: Prisma.JsonValue;
        preciosPorDia: Prisma.JsonValue;
        diasBloqueados: Prisma.JsonValue;
        impuestosIds: string[];
        status: import(".prisma/client").$Enums.SpaceStatus;
        description: string;
        color: string | null;
        tags: Prisma.JsonValue;
        spaceType: string;
        material: string | null;
        width: Prisma.Decimal | null;
        height: Prisma.Decimal | null;
        measureUnit: string | null;
        location: string | null;
        allowsAgreement: boolean;
        planoPdf: string;
        geographicMap: string | null;
        isDigital: boolean;
        images: Prisma.JsonValue;
    }>;
}
export {};
